# Generated by Django 4.1.7 on 2023-04-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baseconfigtable',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('log_createdate', models.DateField(blank=True, db_column='Log_CreateDate', null=True)),
                ('log_createby', models.BigIntegerField(blank=True, db_column='Log_CreateBy', null=True)),
                ('log_updatedate', models.DateField(blank=True, db_column='Log_UpdateDate', null=True)),
                ('log_updateby', models.BigIntegerField(blank=True, db_column='Log_UpdateBy', null=True)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=500, null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted')),
            ],
            options={
                'db_table': 'BaseConfigTable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConfigimpactTour',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('log_createdate', models.DateField(blank=True, db_column='Log_CreateDate', null=True)),
                ('log_createby', models.BigIntegerField(blank=True, db_column='Log_CreateBy', null=True)),
                ('log_updatedate', models.DateField(blank=True, db_column='Log_UpdateDate', null=True)),
                ('log_updateby', models.BigIntegerField(blank=True, db_column='Log_UpdateBy', null=True)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=500, null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted')),
                ('tourproperty', models.CharField(blank=True, db_column='TourProperty', max_length=500, null=True)),
                ('tourimpact', models.BooleanField(blank=True, db_column='TourImpact', null=True)),
            ],
            options={
                'db_table': 'ConfigImpact_Tour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConfigweightService',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('log_createdate', models.DateField(blank=True, db_column='Log_CreateDate', null=True)),
                ('log_createby', models.BigIntegerField(blank=True, db_column='Log_CreateBy', null=True)),
                ('log_updatedate', models.DateField(blank=True, db_column='Log_UpdateDate', null=True)),
                ('log_updateby', models.BigIntegerField(blank=True, db_column='Log_UpdateBy', null=True)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=500, null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted')),
                ('serviceproperty', models.CharField(blank=True, db_column='ServiceProperty', max_length=500, null=True)),
                ('serviceweight', models.IntegerField(blank=True, db_column='ServiceWeight', null=True)),
            ],
            options={
                'db_table': 'ConfigWeight_Service',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConfigweightTour',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('log_createdate', models.DateField(blank=True, db_column='Log_CreateDate', null=True)),
                ('log_createby', models.BigIntegerField(blank=True, db_column='Log_CreateBy', null=True)),
                ('log_updatedate', models.DateField(blank=True, db_column='Log_UpdateDate', null=True)),
                ('log_updateby', models.BigIntegerField(blank=True, db_column='Log_UpdateBy', null=True)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=500, null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted')),
                ('tourproperty', models.CharField(blank=True, db_column='TourProperty', max_length=500, null=True)),
                ('weight', models.IntegerField(blank=True, db_column='Weight', null=True)),
            ],
            options={
                'db_table': 'ConfigWeight_Tour',
                'managed': False,
            },
        ),
    ]
